#!/usr/bin/env perl
use Mojolicious::Lite -signatures;

use lib 'lib';
use V073::Data;

### Preparations

# Load configuration data
plugin NotYAMLConfig => {
    file => $ENV{V073_CONFIG_FILE} // 'config.yml',
};

# Prepare data model
helper data => sub ($self, $rs) {
    state $cdb  = app->config('db');
    state $data = V073::Data->new(
        db_file     => $ENV{V073_DB} // app->home->rel_file($cdb->{file}),
        schema_file => app->home->rel_file($cdb->{schema_file}),
    );
    return $data->helper($rs);
};

# Insert default types/options from configuration
my $default_options = app->config('voting')->{default_options};
while (my ($type_name, $option_names) = each %$default_options) {

    # Already exists
    next if app->data('Type')->count({name => $type_name});

    # Create type and options
    my $type = app->data('Type')->create({name => $type_name});
    $type->create_related(options => {text => $_}) for @$option_names;

    # Add abstention option
    my $abstention = app->config('voting')->{abstention};
    $type->create_related(options => {text => $abstention});
}

# Token helper helper
sub _generate_token ($len) {
    my @chars = ('A'..'Z', '0'..'9');
    return join '' => map $chars[rand @chars] => 1 .. $len;
}

# Helper to generate new unique tokens
helper token => sub ($self) {
    my $token   = _generate_token($self->config('token_length'));
    my $voting  = $self->data('Voting')->count({token => $token});
    my $vote    = $self->data('Token')->count({name => $token});
    $token      = $self->token if $voting or $vote;
    return $token;
};

### Serve the frontend

plugin Webpack => {
    process         => [qw(js css vue v073)],
    dependencies    => {v073 => [qw(
        vue-router
        vue-material
    )]},
};

### Actions

get '/' => 'frontend';

post '/token-type' => sub ($c) {
    my $token = $c->param('token');

    # No token at all?
    return $c->render(status => 403, text => 'No token given')
        unless defined $token;

    # Is it a voting ("admin") token?
    return $c->render(json => {type => 'voting'})
        if $c->data('Voting')->count({token => $token});

    # Is it a vote token?
    return $c->render(json => {type => 'vote'})
        if $c->data('Token')->count({name => $token});

    # Neither?
    return $c->render(status => 404, text => 'Token not found');
};

group { under '/types';

    get '/' => sub ($c) { $c->redirect_to('default_types') };
    get '/default' => sub ($c) {

        # Retrieve types with options as simple data structure
        my @types = $c->data('Type')->search({}, {
            order_by => 'options.id',
            prefetch => 'options',
        });

        # Compactify: {name => [Option texts]...}
        my %type = map { my $type = $_;
            $type->name => [ map $_->text => $type->options ]
        } @types;

        # Done
        $c->render(json => \%type);

    } => 'default_types';
};

app->start;

__DATA__

@@ frontend.html.ep
% my $viewport = 'width=device-width,initial-scale=1,minimal-ui';
% my $font_url = '//fonts.googleapis.com/css?family=Roboto:400,500,700,400italic|Material+Icons';
<!doctype html>
<html>
    <head>
        %= t meta => (name => 'viewport', content => $viewport)
        %= t title => 'v073'
        %= asset 'frontend.css'
        %= stylesheet $font_url
    </head>
    <body>
        %= t div => (id => 'v073-frontend')
        %= asset 'frontend.js'
    </body>
</html>
