<template>
    <div id="about-v073">
        <div id="about">
            <h1>About v073</h1>
            <p>v073 - a "hacker" jargon notation for "vote" - is an easy-to-use and secure tool to set up secret votings. Users do not need to log in or give away any personal data to set up a voting or cast a vote. Access is managed via <em>tokens</em> like "H3LLY34H" generated by the system. The data model is designed to be unable to store any personal information regarding votes or general usage.</p>
        </div>
        <div id="open-source">
            <h2>v073 is open source</h2>
            <p>It is released under the <a class="white-text" href="https://choosealicense.com/licenses/mit/">MIT license</a>, one of the most-free open source licenses in the world. Therefore, v073 is free to use, to set up, extend and redistribute. Everyone is encouraged to visit the <a class="white-text" href="https://github.com/v073/v073">source repository on GitHub</a> to understand the tool, how data is stored, to report bugs and help to improve it.</p>
        </div>
    </div>
</template>

<script>
module.exports = {
    name: 'About',
}
</script>
